### ISSUE TITLE
CompatHelper doesn't seem to be working

### ISSUE THREAD

**Issue by avik-pal** [PumasAI/SimpleChains.jl#163]
https://github.com/PumasAI/SimpleChains.jl/actions/runs/9769652752/job/26969497936.

**Comment by andreasnoack** [comment]
We need to add the https://github.com/JuliaRegistries/CompatHelper.jl/blob/e72bd6b815a69d14ccdb0c85b3589bed2a2af704/.github/workflows/CompatHelper.yml#L6-L8 part. We can do that once CI is passing again.
