### ISSUE TITLE
Issue with introductory example

### ISSUE THREAD

**Issue by rahulunair** [PumasAI/SimpleChains.jl#99]
There is an issue when we are passing StaticInt to randn (See below stack trace), the fix could be multiplying with `1`. I am pushing a patch for the same, kindly let me know if that fix is good enough. I am able to run the example with that change.

```julia
julia> p = randn(SimpleChains.numparam(schain))
ERROR: MethodError: no method matching randn(::Static.StaticInt{216})
Closest candidates are:
  randn() at /usr/local/bin/julia-1.7.3/share/julia/stdlib/v1.7/Random/src/normal.jl:38
  randn(::Integer...) at /usr/local/bin/julia-1.7.3/share/julia/stdlib/v1.7/Random/src/normal.jl:244
  randn(::Tuple{Vararg{Int64, N}} where N) at /usr/local/bin/julia-1.7.3/share/julia/stdlib/v1.7/Random/src/normal.jl:243
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[28]:1
```

**Comment by chriselrod** [comment]
It should be using `init_patams` instead

**Comment by rahulunair** [comment]
Hi @chriselrod , thank you for the comment, I have updated the PR, kindly review and let me know if it makes sense.
